"""Compact extra topics so each category can fill a 10-planet sky.

Featured topics (the original hand-written ten) live in generate_demo_data.py
and are looked up by name. Everything else is synthesized from this roster.
"""

from __future__ import annotations

# Ranked loudest → quietest inside each category. The first slots are heavy
# enough that the default "All" sky is a mix, not one category's entire roster.
CATEGORY_ROSTERS: dict[str, list[str]] = {
    "Technology": [
        "AI Futures",
        "Digital Privacy",
        "Platform Power",
        "Chip Race",
        "Open Source",
        "Cyber Attacks",
        "Smart Cities",
        "Biotech Tools",
        "Space Industry",
        "App Stores",
    ],
    "Economy": [
        "Housing Costs",
        "Labor Markets",
        "Inflation Fight",
        "Small Business",
        "Trade Wars",
        "Care Economy",
        "Wall Street",
        "Student Economy",
        "Crypto Winter",
        "Public Debt",
    ],
    "Politics": [
        "Border Policy",
        "Voting Access",
        "Court Power",
        "Campaign Money",
        "Policing",
        "Foreign Wars",
        "Tax Fights",
        "Statehouses",
        "Protest Rights",
        "Executive Power",
    ],
    "Environment": [
        "Climate Policy",
        "Water Crisis",
        "Grid Transition",
        "Air Quality",
        "Biodiversity",
        "Farm Weather",
        "Plastic Waste",
        "Ocean Heat",
        "Mining Boom",
        "Conservation Land",
    ],
    "Health": [
        "Public Health",
        "Hospital Staffing",
        "Aging Care",
        "Reproductive Care",
        "Addiction Policy",
        "Disability Access",
        "Pandemic Memory",
        "Food Systems",
        "Sleep Crisis",
        "Longevity Hype",
    ],
    "Entertainment": [
        "Franchise Fatigue",
        "Concert Economy",
        "Creator Burnout",
        "Gaming Culture",
        "Streaming Queue",
        "Awards Season",
        "Fandom Wars",
        "Comedy Scene",
        "Theater Revival",
        "Reality TV",
    ],
    "Sports": [
        "Sports Culture",
        "League Labor",
        "College Sports",
        "Soccer Boom",
        "Women's Leagues",
        "Stadium Deals",
        "Esports",
        "Injury Culture",
        "Olympic Politics",
        "Referee Wars",
    ],
    "Education": [
        "Education Reform",
        "College Value",
        "AI in Class",
        "School Safety",
        "Literacy",
        "Admissions",
        "Community College",
        "Faculty Labor",
        "EdTech Fatigue",
        "Civics Teaching",
    ],
    "Media": [
        "Media Trust",
        "Newsroom Cuts",
        "Streaming Wars",
        "Deepfakes",
        "Podcast Politics",
        "Comment Sections",
        "Public Broadcasting",
        "Book Culture",
        "Celebrity News",
        "Documentary Boom",
    ],
    "Religion": [
        "Church and State",
        "Youth Faith",
        "Religious Freedom",
        "Clergy Abuse",
        "Interfaith Cities",
        "Secular Surge",
        "Mutual Aid Faith",
        "Ritual Online",
        "Sacred Land",
        "Evangelical Politics",
    ],
}

# Relative mass of each category in the week. Uneven on purpose so the default
# sky can include several Politics planets and none from quieter categories.
CATEGORY_WEIGHTS: dict[str, int] = {
    "Technology": 18,
    "Economy": 16,
    "Politics": 13,
    "Environment": 11,
    "Health": 10,
    "Entertainment": 9,
    "Sports": 8,
    "Education": 7,
    "Media": 5,
    "Religion": 3,
}

# Share of a category's mass for planet ranks 1–10 (sun → pluto).
TOPIC_CURVE = [28, 18, 13, 10, 8, 7, 6, 4, 3, 3]

FACE_TITLES: dict[str, list[str]] = {
    "Platform Power": ["App Bans", "Store Fees", "Moderation", "Antitrust", "Creator Cuts"],
    "Chip Race": ["Export Controls", "Fab Jobs", "Taiwan Risk", "Consumer Prices"],
    "Open Source": ["Maintainer Burnout", "Corporate Capture", "License Fights", "Security Holes"],
    "Cyber Attacks": ["Ransomware", "Hospital Hits", "State Actors", "Password Fatigue"],
    "Smart Cities": ["Sensor Streets", "Vendor Lock-in", "Traffic AI", "Public Records"],
    "Biotech Tools": ["Gene Editing", "Lab Access", "Patent Thickets", "Clinic Ethics"],
    "Space Industry": ["Launch Cadence", "Debris", "Moon Contracts", "Tourism"],
    "App Stores": ["Sideloading", "Teen Safety", "Search Bias", "Small Devs"],
    "Inflation Fight": ["Grocery Bills", "Rate Hikes", "Corporate Margins", "Wage Lag"],
    "Small Business": ["Rent and Cards", "Hiring", "Main Street", "Platform Fees"],
    "Trade Wars": ["Tariffs", "Factory Moves", "Farm Exports", "Chip Supply"],
    "Care Economy": ["Childcare", "Home Health", "Unpaid Hours", "Public Options"],
    "Wall Street": ["Index Funds", "Buybacks", "Bank Rules", "Retail Traders"],
    "Student Economy": ["Side Gigs", "Campus Work", "Loan Math", "First Apartments"],
    "Crypto Winter": ["Exchange Failures", "Stablecoins", "True Believers", "Regulation"],
    "Public Debt": ["Interest Costs", "Ceiling Fights", "Austerity", "Tax Base"],
    "Voting Access": ["Early Voting", "ID Laws", "Mail Ballots", "Purge Lists"],
    "Court Power": ["Emergency Dockets", "Ethics", "State Courts", "Precedent"],
    "Campaign Money": ["Dark Money", "Small Donors", "PACs", "Platform Ads"],
    "Policing": ["Use of Force", "City Budgets", "Body Cams", "Union Contracts"],
    "Foreign Wars": ["Aid Packages", "Draft Talk", "Refugee Waves", "War Fatigue"],
    "Tax Fights": ["Rate Brackets", "Loopholes", "Local Levies", "Wealth Taxes"],
    "Statehouses": ["Preemption", "School Bills", "Maps", "Attorneys General"],
    "Protest Rights": ["Permits", "Campus Rules", "Kettling", "Night Marches"],
    "Executive Power": ["Emergency Orders", "Agencies", "Appointments", "Norms"],
    "Water Crisis": ["Aquifers", "City Rations", "Farm Wells", "Pipe Lead"],
    "Grid Transition": ["Baseload", "Batteries", "Interconnects", "Ratepayers"],
    "Air Quality": ["Wildfire Smoke", "Ports", "Asthma", "Diesel"],
    "Biodiversity": ["Extinctions", "Land Trusts", "Invasives", "Insect Drop"],
    "Farm Weather": ["Crop Insurance", "Drought", "Flood Years", "Co-ops"],
    "Plastic Waste": ["Packaging", "Recycling Myths", "Ocean Gyres", "Refill Shops"],
    "Ocean Heat": ["Coral", "Fisheries", "Sea Level", "Marine Heatwaves"],
    "Mining Boom": ["Lithium", "Tribal Land", "Tailings", "Critical Minerals"],
    "Conservation Land": ["Public Access", "Working Forests", "Easements", "Firebreaks"],
    "Hospital Staffing": ["Travel Nurses", "Closures", "Ratios", "Burnout"],
    "Aging Care": ["Nursing Homes", "Medicare Gaps", "Family Leave", "Isolation"],
    "Reproductive Care": ["Clinic Access", "Medication", "Travel", "Employers"],
    "Addiction Policy": ["Overdose", "Treatment Beds", "Safe Supply", "Courts"],
    "Disability Access": ["Transit", "Workplaces", "Benefits Cliffs", "Devices"],
    "Pandemic Memory": ["Long Covid", "School Years", "Trust", "Stockpiles"],
    "Food Systems": ["Ultra-processed", "School Meals", "Farm Workers", "Price"],
    "Sleep Crisis": ["Shift Work", "Screens", "Clinics", "Kids"],
    "Longevity Hype": ["Supplements", "Biohackers", "Clinic Tourism", "Evidence"],
    "Franchise Fatigue": ["Sequel Glut", "Ticket Prices", "Originals", "IP Law"],
    "Concert Economy": ["Dynamic Tickets", "Fees", "Openers", "Venue Monopolies"],
    "Creator Burnout": ["Algorithm Churn", "Brand Deals", "Mental Health", "Unions"],
    "Gaming Culture": ["Crunch", "Live Service", "Mods", "Toxicity"],
    "Streaming Queue": ["Password Rules", "Show Cancellations", "Discovery", "Ads"],
    "Awards Season": ["Campaigns", "Snubs", "Box Office", "Craft"],
    "Fandom Wars": ["Shipping", "Leaks", "Harassment", "Canon"],
    "Comedy Scene": ["Clubs", "Specials", "Cancel Talk", "Podcasts"],
    "Theater Revival": ["Touring Costs", "Broadway", "School Plays", "Grants"],
    "Reality TV": ["Labor", "Editing", "Fame Pipeline", "Products"],
    "League Labor": ["Lockouts", "Revenue Split", "Minors", "Media Rights"],
    "College Sports": ["NIL", "Transfers", "Conferences", "Academics"],
    "Soccer Boom": ["MLS", "Women's Game", "World Cup", "Local Clubs"],
    "Women's Leagues": ["Pay Gaps", "Facilities", "Coverage", "Investment"],
    "Stadium Deals": ["Public Money", "Naming Rights", "Displacement", "Parking"],
    "Esports": ["Orgs", "Burnout", "Prizing", "Broadcasts"],
    "Injury Culture": ["Concussion", "Load Management", "Youth", "Painkillers"],
    "Olympic Politics": ["Host Costs", "Boycotts", "Athletes", "Broadcast"],
    "Referee Wars": ["VAR", "Abuse", "Pay", "Consistency"],
    "College Value": ["ROI", "Humanities", "Trade Paths", "Rankings"],
    "AI in Class": ["Cheating", "Tutors", "Policy", "Equity"],
    "School Safety": ["Drills", "Counselors", "Design", "Police"],
    "Literacy": ["Phonics", "Screens", "Libraries", "Tutors"],
    "Admissions": ["Testing", "Legacy", "Essays", "Yield"],
    "Community College": ["Transfer", "Workforce", "Funding", "Childcare"],
    "Faculty Labor": ["Adjuncts", "Tenure", "Strikes", "Research"],
    "EdTech Fatigue": ["Licenses", "Surveillance", "PD", "Outages"],
    "Civics Teaching": ["Curriculum", "Polarization", "Local Gov", "Media"],
    "Newsroom Cuts": ["Buyouts", "Beats", "Private Equity", "Nonprofits"],
    "Streaming Wars": ["Bundles", "Sports Rights", "Churn", "Originals"],
    "Deepfakes": ["Elections", "Porn", "Watermarks", "Law"],
    "Podcast Politics": ["Hosts", "Ads", "Parties", "Clips"],
    "Comment Sections": ["Moderation", "Anonymity", "Rage Bait", "Local"],
    "Public Broadcasting": ["Funding", "Bias Fights", "Rural", "Kids"],
    "Book Culture": ["Bans", "Indie Shops", "BookTok", "Advances"],
    "Celebrity News": ["Paparazzi", "PR", "Stans", "Privacy"],
    "Documentary Boom": ["True Crime", "Access", "Streaming", "Ethics"],
    "Church and State": ["School Prayer", "Tax Status", "Hospitals", "Monuments"],
    "Youth Faith": ["Nones", "Campus Groups", "TikTok", "Parents"],
    "Religious Freedom": ["Exemptions", "Workplaces", "Minorities", "Courts"],
    "Clergy Abuse": ["Records", "Settlements", "Survivors", "Reform"],
    "Interfaith Cities": ["Shared Space", "Holidays", "Safety", "Food"],
    "Secular Surge": ["Unbelief", "Ritual Lite", "Politics", "Community"],
    "Mutual Aid Faith": ["Shelters", "Food Banks", "Disaster", "Volunteers"],
    "Ritual Online": ["Livestreams", "Apps", "Grief", "Attention"],
    "Sacred Land": ["Burial Sites", "Pipelines", "Parks", "Repatriation"],
    "Evangelical Politics": ["Primary Voters", "Media", "Young Exit", "Policy"],
}
